# Generated by Django 3.0.6 on 2020-05-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fares',
            name='fare_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
