# Generated by Django 3.0.6 on 2020-05-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200526_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fares',
            name='payment_method',
        ),
        migrations.AlterField(
            model_name='fares',
            name='currency_type',
            field=models.CharField(default='KSH', editable=False, max_length=10),
        ),
    ]
