# Generated by Django 3.0.6 on 2020-05-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200526_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='fares',
            name='period',
            field=models.CharField(default='11:00 - 1:00', max_length=100),
        ),
    ]
