# Generated by Django 3.0.6 on 2020-06-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200527_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='max_fare',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='routes',
            name='min_fare',
            field=models.IntegerField(default=60),
        ),
    ]
