# Generated by Django 3.0.6 on 2020-06-03 12:35

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200603_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='max_fare',
            field=models.IntegerField(default=api.models.random_max),
        ),
        migrations.AlterField(
            model_name='routes',
            name='min_fare',
            field=models.IntegerField(default=api.models.random_min),
        ),
    ]
