# Generated by Django 3.0.6 on 2020-06-04 11:09

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200603_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='max_fare',
            field=models.IntegerField(default=api.models.random_max, null=True),
        ),
        migrations.AlterField(
            model_name='routes',
            name='min_fare',
            field=models.IntegerField(default=api.models.random_min, null=True),
        ),
    ]
